rustler::atoms! {
    ok,
    error,
    vsn1,
    notfound,
    undefined,
    end_of_iterator,
    unknown_cf,
    snap,
    backup,
    // Merge operation atoms
    int_add,
    list_append,
    list_subtract,
    list_set,
    list_delete,
    list_insert,
    binary_append,
    binary_erase,
    binary_insert,
    binary_replace,
}
